version: '3.9'
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
    build: .
    image: flyhead/buybook:1
    environment:
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_ROUTINGKEY: "buybook_search"
      PYTHONPATH: "/usr/local/src"
    volumes:
      - ./buybook:/usr/local/src/buybook
      - ./buybook/component:/usr/local/src/buybook/component
#      - D:\\workspace\\citest\\BuyBook\\buybook\\component\cURL.bash:/usr/local/BuyBook/buybook/component/cURL.bash
    command: "python /usr/local/src/buybook/worker.py"
    depends_on:
      - rabbitmq

  web_client:
    image: flyhead/buybook:1
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: "/usr/local/src/buybook/web_client.py"
#      ENV FLASK_RUN_HOST: "0.0.0.0"
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_ROUTINGKEY: "buybook_search"
      PYTHONPATH: "/usr/local/src"
    volumes:
      - ./buybook:/usr/local/src/buybook
    command: "python -m flask run -h 0.0.0.0"
    depends_on:
      - rabbitmq

